### ISSUE TITLE
How to Perform Flash Attention Backward Pass When N_CTX % 128 != 0

### ISSUE THREAD

**Issue by zhaohm14** [ROCmSoftwarePlatform/triton#666]
Hi,

I've noticed that when performing the backward pass with Flash Attention, N_CTX (the context length) is required to be a multiple of 128, as specified here:

https://github.com/ROCm/triton/blob/94961d99838ec046a65cdd0eb02500fb8d05f659/python/perf-kernels/flash-attention.py#L1026 

In my use case, N_CTX is not divisible by 128, and I'm curious about what happens when processing such a tensor. I tried commenting out the line that enforces this constraint to observe the behavior, and I found that the backward pass results became incorrect.

I want to know that what is the original reason for requiring N_CTX to be divisible by 128? And could this problem be related to how tensor boundaries are handled? Is there a proper way to adjust the code so that the backward pass works correctly when N_CTX isn't a multiple of 128?

Thank you very much for your help!

**Comment by tcgu-amd** [comment]
Hi @zhaohm14, thanks for reaching out! Without getting into the details, yes, it has to be divisible by 128 due to both hardware and algorithmic constraints (you might get away with divisible by 64 as well but there might be accuracy issues). I would recommend padding the context such that it becomes a multiple of 128 for you program to work correctly. Thanks!

**Comment by zhaohm14** [comment]
Thank you!
